const cities=[
    
    {_Id:0, 
        name:"Barcelona",
        imgUrl:"/barcelona.jpg",
        alt:"Barcelona City",
        country:"Spain",
        language: "Spanish, catalan",
        currency:"Euro",
        population:"1.6 million",
        info: "Is a city on the northeastern coast of Spain. It is the capital and largest city of the autonomous community of Catalonia, as well as the second most populous municipality of Spain. With a population of 1.6 million within city limits, its urban area extends to numerous neighbouring municipalities within the province of Barcelona and is home to around 4.8 million people.",
       },
       {_Id:1, 
        name:"Belfast",
        imgUrl:"/belfast.jpg",
        alt:"Belfast City",
        country:"Northern Ireland",
        language: "English",
        currency: "Pound sterling",
        population:"293,298",
        info: "Belfast from Irish, meaning 'mouth of the sand-bank ford' is the capital and largest city of Northern Ireland, standing on the banks of the River Lagan on the east coast. It is the 10th-largest primary urban area in the United Kingdom and the second-largest city in Ireland. The population of the Belfast metropolitan area was 671,559 in 2011, the City of Belfast had a population of 293,298.",

       },
       {_Id:2, 
        name:"Budapest",
        imgUrl:"/budapest.jpg",
        alt:"Budapest",
        country:"Hungary",
        language:"",
        currency:"Forint",
        population:"1.7 million",
        info:"Is the capital and most populous city of Hungary. It is the ninth-largest city in the European Union by population within city limits and the second-largest city on the Danube river; the city has an estimated population of 1,752,286 over a land area of about 525 square kilometres (203 square miles).Budapest, which is both a city and county.",
       },
       {_Id:3, 
        name:"Edimburgh",
        imgUrl:"/edimburg.jpg",
        alt:"Edimburgh City",
        country:"Scotland",
        language:"English",
        currency:"Pound sterling",
        population:"506,520",
        info:"Is the capital city of Scotland and one of its 32 council areas. It is located in the historic region of Lothian, on the southern shore of the Firth of Forth. Edinburgh is Scotland's second-most populous city, after Glasgow, and the seventh-most populous city in the United Kingdom. Recognised as the capital of Scotland since at least the 15th century, Edinburgh is the seat of the Scottish Government.",
        
       },
       {_Id:4, 
        name:"Helsinki",
        imgUrl:"/helsinki.jpg",
        alt:"Helsinki City",
        country:"Finland",
        language:"Finnish",
        currency:"Euro",
        population:"665,558",
        info:"Is the capital, primate, and most populous city of Finland. Located on the shore of the Gulf of Finland, it is the seat of the region of Uusimaa in southern Finland and has a population of 665,558. The city's urban area has a population of 1,268,296,[12] making it by far the most populous urban area in Finland as well as the country's most important center for politics, education, finance, culture, and research.",
       },
       {_Id:5, 
        name:"Jakarta",
        imgUrl:"/jakarta.jpg",
        alt:"Jakarta City",
        country:"Indonesia",
        language:"Indonesian",
        currency:"Indonesian Rupiah",
        population:"10,679,951",
        info:"Is the capital and largest metropolis of Indonesia. Lying on the northwest coast of Java, the world's most populous island, Jakarta is the largest metropole in Southeast Asia, and serves as the diplomatic capital of ASEAN. Jakarta is the economic, cultural, and political centre of Indonesia. It possesses a province-level status and has a population of 10,679,951 as of mid-2022",
       },
       {_Id:6, 
        name:"La Plata",
        imgUrl:"/laplata.jpg",
        alt:"La Plata City",
        country:"Argentina",
        language:"Spanish",
        currency:"Peso",
        population:"0.772 million",
        info:" is the capital city of Buenos Aires Province, Argentina. According to the 2022 census, it has a population of 772,618 and its metropolitan area, the Greater La Plata, has 938,287 inhabitants. It is located 9 kilometers (6 miles) inland from the southern shore of the Río de la Plata estuary. La Plata was planned and developed to serve as the provincial capital after the city of Buenos Aires was federalized in 1880. It was officially founded by Governor Dardo Rocha on 19 November 1882.",
       },
       {_Id:7, 
        name:"Lima",
        imgUrl:"/lima.jpg",
        alt:"Lima City",
        country:"Peru",
        language:"Spanish",
        currency:"Sol peruano",
        population:"10,092,000",
        info:"Originally founded as Ciudad de Los Reyes (City of The Kings), is the capital and largest city of Peru. It is located in the valleys of the Chillón, Rímac and Lurín Rivers, in the desert zone of the central coastal part of the country, overlooking the Pacific Ocean. The city is considered the political, cultural, financial and commercial center of Peru. Due to its geostrategic importance, the Globalization and World Cities Research Network has categorized it as a 'beta' tier city.",
       },
       {_Id:8, 
        name:"Ljubljana",
        imgUrl:"/ljubljana.jpg",
        alt:"Ljubljana City",
        country:"Slovenia",
        language:"Slovenian",
        currency:"Euro",
        population:"295,504",
        info:"Is the capital and largest city of Slovenia, located along a trade route between the northern Adriatic Sea and the Danube region, north of the country's largest marsh, inhabited since prehistoric times. It is the country's cultural, educational, economic, political and administrative center. During antiquity, a Roman city called Emona stood in the area. The city was first mentioned in the first half of the 12th century. It was the historical capital of Carniola, one of the Slovene-inhabited parts of the Habsburg monarchy. It was under Habsburg rule from the Middle Ages until the dissolution of the Austro-Hungarian Empire in 1918.",
       },
       {_Id:9, 
        name:"Nassau",
        imgUrl:"/nassau.jpg",
        alt:"Nassau City",
        country:"The Bahamas",
        language:"English",
        currency:"Bahamian dollar",
        population:"305,329",
        info:"Is the capital and largest city of The Bahamas. It is located on the island of New Providence, which had a population of 246,329 in 2010, or just over 70% of the entire population of The Bahamas. As of april of 2023, the preliminary results of the 2022 census of the Bahamas reported a population of 296,522 for New Providence, 74.26% of the country's population.[4] Nassau is commonly defined as a primate city, dwarfing all other towns in the country. It is the centre of commerce, education, law, administration, and media of the country.",
       },
       {_Id:10, 
        name:"Tokio",
        imgUrl:"/tokio.jpg",
        alt:"Tokio City",
        country:"Japan",
        language:"Japanese",
        currency:"Japanese Yen",
        population:"14.09 million",
        info:"Officially the Tokyo Metropolis, is the capital and the most populous prefecture of Japan. Tokyo's metropolitan area (including neighboring prefectures, 13,452 square kilometers or 5,194 square miles) is the most populous in the world, with an estimated 37.468 million residents as of 2018; although this number has been gradually decreasing since then, the prefecture itself has a population of 14.09 million people while the prefecture's central 23 special wards have a population of 9.73 million. Located at the head of Tokyo Bay, the prefecture forms part of the Kantō region on the central coast of Honshu, Japan's largest island. Tokyo serves as Japan's economic center and is the seat of both the Japanese government and the Emperor of Japan.",
       },
       {_Id:11, 
        name:"Vienna",
        imgUrl:"/vienna.jpg",
        alt:"Vienna City",
        country:"Austria",
        language:"German",
        currency:"Euro",
        population:"1,951,354",
        info:"Is the capital, largest city, and one of nine provinces of Austria. Vienna is Austria's most populous city and its primate city, with about two million inhabitants (2.9 million within the metropolitan area, nearly one-third of the country's population), and its cultural, economic, and political center. It is the sixth-largest city proper by population in the European Union and the largest of all cities on the Danube river.",
       },
       {_Id:12, 
        name:"Tunis",
        imgUrl:"/tunis.jpg",
        alt:"Tunis City",
        country:"Tunisia",
        language:"Modern Standard Arabic",
        currency:"The dinar",
        population:"2,700,000",
        info:"Is the capital and largest city of Tunisia. The greater metropolitan area of Tunis, often referred to as 'Grand Tunis', has about 2,700,000 inhabitants. As of 2020, it is the third-largest city in the Maghreb region (after Casablanca and Algiers) and the eleventh-largest in the Arab world. Situated on a large Mediterranean Sea gulf (the Gulf of Tunis), behind the Lake of Tunis and the port of La Goulette (Ḥalq il-Wād), the city extends along the coastal plain and the hills that surround it. At its core lies the Medina, a World Heritage Site",
       },      
       {_Id:13, 
        name:"Moscow",
        imgUrl:"/moscow.jpg",
        alt:"Moscow City",
        country:"Russia",
        language:"Russian",
        currency:"The ruble",
        population:"13.0 million",
        info:"Is the capital and largest city of Russia. The city stands on the Moskva River in Central Russia, with a population estimated at 13.0 million residents within the city limits, over 18.8 million residents in the urban area, and over 21.5 million residents in the metropolitan area. The city covers an area of 2,511 square kilometers (970 sq mi), while the urban area covers 5,891 square kilometers (2,275 sq mi), and the metropolitan area covers over 26,000 square kilometers (10,000 sq mi). Moscow is among the world's largest cities, being the most populous city entirely in Europe, the largest urban and metropolitan area in Europe, and the largest city by land area on the European continent.",
       },      
       {_Id:14, 
        name:"Cape Town",
        imgUrl:"/capetown.jpg",
        alt:"Cape Town City",
        country:"South Africa",
        language:"English, Afrikaans, Swati",
        currency:"Rand",
        population:"4,710,000",
        info:"Is the legislative capital of South Africa. It is the country's oldest city and the seat of the Parliament of South Africa. It is the country's second-largest city, after Johannesburg, and the largest in the Western Cape. The city is part of the City of Cape Town metropolitan municipality. The city is known for its harbour, its natural setting in the Cape Floristic Region, and for landmarks such as Table Mountain and Cape Point. In 2014, Cape Town was named the best place in the world to visit by The New York Times and similarly by The Daily Telegraph in 2016. Located on the shore of Table Bay, the City Bowl area of Cape Town is the oldest urban area in the Western Cape, with a significant cultural heritage.",
       },
                            
]

export default cities;